feat: add BPDM authentication configuration for 24.08. release
eclipse-tractusx/portal-iam pull request #155
Opened 2024-07-23 05:57 UTC by nicoprow

## Description

This pull request adjusts the Central-IDP realm configuration to be more align with the BPDM default authentication configuration for the release 24.08. / BPDM version 6.1.0 as described [here](https://github.com/eclipse-tractusx/bpdm/blob/release/6.1.x/docs/arc42/arc42-bpdm.md#authentication--autorization)

- add Orchestrator client and permissions
- add Orchestrator roles
- add service accounts for Gate, Pool and Cleaning Service Dummy
- add service accounts for EDC
- change some names and descriptions for existing BPDM service accounts to better match their purporse

## Why

Currently, the configuration between the Central-IDP and BPDM is not completely aligned. This leads to more complexity and configuration overhead for operators. Also, currently Central-IDP is missing some technical users/service accounts which is needed by an authenticated golden record process. By providing these initial service accounts an operator does not need to adapt the keycloak realm when setting up the the basic golden record process.

## Issue

#154 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/14.%20How%20to%20contribute.md)
- [x] I have added copyright and license headers, footers (for .md files) or files (for images) 
- [x] I have performed a self-review of my changes
- [x] I have successfully tested my changes
- [x] I have added comments in the default values.yaml file with helm-docs syntax ('# -- ') if relevant for installation
- [x] I have commented my changes, particularly in hard-to-understand areas

2024-08-07 12:36 UTC, evegufy approved these changes
Looks good!
Could you please also update the [R&Rs](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md) and list of [clients/service-accounts](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/03.%20Clients.md#initial-clients-and-service-accounts)

2024-08-07 12:36 UTC, evegufy requested changes
Looks good!
Could you please also update the [R&Rs](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md) and list of [clients/service-accounts](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/03.%20Clients.md#initial-clients-and-service-accounts)

2024-09-13 14:45 UTC, evegufy commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -                "read_changelog_member"
I think those role assignments to the composite role `Business Partner Data Manager` of the portal client are needed to enable the portal-bpdm integration, please don't remove them

2024-09-13 14:46 UTC, evegufy commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -              ],
I think those role assignments to the composite role `Company Admin` of the portal client are needed to enable the portal-bpdm integration, please don't remove them

2024-09-18 10:42 UTC, typecastcloud commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -                "read_changelog_member"
Hi @evegufy, I think the idea is to get these roles via "BPDM Pool Consumer" instead. Also makes it easier to adjust pool consumer access later.

2024-09-19 03:15 UTC, nicoprow commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -                "read_changelog_member"
@evegufy @typecastcloud Yes correct, I added the necessary composite roles in the technical_roles_management below. These roles should already contain the roles I deleted here and therefore I removed them

2024-09-19 03:18 UTC, nicoprow commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -              ],
@evegufy Also here the company admin gets read access to the BPDM Pool. These access rights are already included in the "BPDM Pool Consumer" role  in the technical_roles_management

2024-09-19 03:43 UTC, nicoprow commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -                "read_changelog_member"
I can of course also decouple the Portal roles more from the technical roles (which in BPDM at least are the true BPDM defined roles as we do not separate into technical and non-technical roles). For this, I would just add the necessary low-level BPDM roles to the Portal roles and remove the references from the technical_roles. In any case we should either go with just referencing technical roles or no technical roles reference references at all, as I feel that a mix between the two is very confusing

2024-09-19 11:24 UTC, evegufy commented on docs/technical documentation/06. Roles & Rights Concept.md
> +- BPDM Orchestrator Processor PoolSync
In order for that to work, the roles need to be enabled in the seeding data of the portal-backend, see example PRs:
- https://github.com/eclipse-tractusx/portal-backend/pull/623
- https://github.com/eclipse-tractusx/portal-backend/pull/772

Do you want to raise the PR yourself? if not please raise an issue in the portal-backend repo then we can discuss who able to take it over and when.

2024-09-19 11:24 UTC, evegufy commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -                "read_changelog_member"
@nicoprow @typecastcloud I didn't notice the assignment via "BPDM Pool Consumer" --> closing conversation

2024-09-19 11:24 UTC, evegufy commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> -              ],
@nicoprow I didn't notice the assignment via "BPDM Pool Consumer" --> closing conversation

2024-09-19 11:24 UTC, evegufy commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> +      "enabled": false,
that the client is disabled, is on purpose?

2024-09-19 11:26 UTC, evegufy requested changes
Please resolve conflicts in the r&r documentation

2024-09-20 02:59 UTC, nicoprow commented on import/realm-config/generic/catenax-central/CX-Central-realm.json
> +      "enabled": false,
Yea, it is disabled on purpose. To be hontest BPDM does not really need the confidential clients to login, as there are no users who would login over these clients. Rather, currently we use these clients for having a place to store application specific roles. The BPDM applications are aware of the clients as role resources but do not need them for user login purposes. This is done via the service accounts instead. We could have disabled the confidential clients for Pool and Gate as well but I did not want to introduce unnecessary changes for now.

2024-09-20 03:09 UTC, nicoprow commented on docs/technical documentation/06. Roles & Rights Concept.md
> +- BPDM Orchestrator Processor PoolSync
@evegufy  Is that something that should happen in a separate pull request or is it OK to add it in this one? I will try to do it myself first

2024-09-20 03:26 UTC, nicoprow commented on docs/technical documentation/06. Roles & Rights Concept.md
> +- BPDM Orchestrator Processor PoolSync
https://github.com/eclipse-tractusx/portal-backend/issues/1020

2024-09-20 06:29 UTC, evegufy approved these changes

2024-09-20 06:32 UTC, evegufy commented
Hi @typecastcloud would you like to review still or should I go head with the merge?

2024-09-20 06:58 UTC, typecastcloud commented
> Hi @typecastcloud would you like to review still or should I go head with the merge?

I'm not able to find anything that is wrong. Go ahead.

2024-09-20 07:03 UTC, typecastcloud approved these changes
I would have preferred changes to existing portal users and introduction of golden record tech users in separate PRs but otherwise this looks good.

2024-09-20 07:19 UTC, merged