feat(roles): add subscribe_service permission to Business Admin
eclipse-tractusx/portal-iam pull request #173
Opened 2024-08-19 10:42 UTC by typecastcloud

## Description

Add `subscribe_service` to Business Admin composite role. As defined by [permission matrix](https://github.com/eclipse-tractusx/portal-assets/blob/v2.1.0/public/assets/images/content/PortalRoleAndPermissionMatrix.png).

## Why

This missing permission prevented Business Admin from subscribing to services.

## Issue

Refs: eclipse-tractusx/portal-iam#172

## Checklist

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/14.%20How%20to%20contribute.md)
- [ ] I have performed a self-review of my changes
- [ ] I have successfully tested my changes

2024-08-20 06:20 UTC, MaximilianHauer approved these changes

2024-08-22 05:46 UTC, Phil91 approved these changes

2024-09-13 14:56 UTC, evegufy requested changes
Hi @typecastcloud thanks for adding that! could you please also update the [docs](https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.1/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md)?

2024-09-16 07:48 UTC, typecastcloud commented
> Hi @typecastcloud thanks for adding that! could you please also update the [docs](https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.1/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md)?

<img width="600" alt="image" src="https://github.com/user-attachments/assets/68f37c50-d0b6-4f90-b5fa-2d1dec4004eb">
In docs the composite already had the role. Just not in the import realm. Do you mean something else?

2024-09-16 08:31 UTC, evegufy commented
> > Hi @typecastcloud thanks for adding that! could you please also update the [docs](https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.1/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md)?
> 
> <img alt="image" width="600" src="https://private-user-images.githubusercontent.com/150006841/367679595-68f37c50-d0b6-4f90-b5fa-2d1dec4004eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzU2NDgsIm5iZiI6MTcyNjQ3NTM0OCwicGF0aCI6Ii8xNTAwMDY4NDEvMzY3Njc5NTk1LTY4ZjM3YzUwLWQwYjYtNGY5MC1iNWZhLTJkMWRlYzQwMDRlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQwODI5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTc3N2QxYjA4YTNhMjg5NWFiYjk5ZWI3ZTI3NzM4YjkxNjNjZWRjOWQ5ZTBkMWFkMmUzN2ZiY2JmYmU3Nzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aIhNhIDYDRvO_mKw2PzHhTpNYMw2b8LSzXz2P28h_SE">
> Hi @evegufy, in docs matrix the buisness admin composite already had the role. Just not in the import realm. Do you mean something else?

Hi @typecastcloud you're right, I overlooked that, sorry.

2024-09-16 08:31 UTC, evegufy approved these changes

2024-09-16 08:31 UTC, merged