docs: 187 align portal iam doc structure with trg 1
eclipse-tractusx/portal-iam pull request #207
Opened 2024-10-15 05:12 UTC by shahmargi12

## Description

- **Restructured existing documents** according to the new TRG 1 folder hierarchy.
- Created a new README.md with links to the relevant files and subfolders, ensuring all documents are properly referenced and accessible.

## Why

To align with TRG 1 

## Issue

#187 

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/14.%20How%20to%20contribute.md)
- [X] I have added copyright and license headers, footers (for .md files) or files (for images) 
- [X] I have performed a self-review of my changes
- [X] I have successfully tested my changes

2024-10-18 05:09 UTC, shahmargi12 commented
Hello @evegufy @MaximilianHauer 

I noticed that the quality gate is failing due to some issues in the YAML files. The only change I made related to these files is moving their folder location, without modifying the content itself.

Could you please take a look and help me resolve the issue? It seems like the errors might be triggered by the folder restructuring.

2024-10-23 11:31 UTC, evegufy commented
> Hello @evegufy @MaximilianHauer
> 
> I noticed that the quality gate is failing due to some issues in the YAML files. The only change I made related to these files is moving their folder location, without modifying the content itself.
> 
> Could you please take a look and help me resolve the issue? It seems like the errors might be triggered by the folder restructuring.

@shahmargi12 thank you for the contribution!
Regarding sonarcloud: could you please add such a file https://github.com/eclipse-tractusx/portal-frontend/blob/main/.sonarcloud.properties where you exclude the docs directory? https://stackoverflow.com/questions/21323276/sonarqube-exclude-a-directory Thank you!

2024-10-24 12:17 UTC, shahmargi12 commented
@evegufy  I’ve updated the .sonarcloud.properties file to exclude the docs directory. You can find the details in this PR: [#1275](https://github.com/eclipse-tractusx/portal-frontend/pull/1275). 
Thank you!

2024-10-25 04:51 UTC, shahmargi12 commented
Hello @evegufy 
Apologies for the previous confusion. I've created a pull request (#222) for the required change in the portal-iam repository.
Let me know if you need any adjustments.

2024-11-06 20:58 UTC, evegufy commented
> Hello @evegufy Apologies for the earlier confusion. I’ve updated the `sonarcloud.properties` file to ignore the .yaml file inside the docs folder.
> 
> Let me know if you need any further adjustments.

@shahmargi12 perfect, thank you! sorry, I didn't remember that there is already a `sonarcloud.properties` and the existing one could to be updated.

2024-11-06 21:10 UTC, evegufy requested changes
I had a look and as architecture and user documentation doesn't exist in this repo, I think it makes sense to restructure like this:

```
repository
└─── docs/
    └─── admin/
         └─── technical-documentation/
         └─── known-knowns/
         └─── dev-process/
         └─── release-process/
    └─── consultation/
         └─── portal-iam-helm.chart.md
         └─── charts/
         └─── environment/
         └─── workshops/
         └─── consultation.md
    └─── README.md

```

2024-11-07 05:28 UTC, shahmargi12 commented
> I had a look and as architecture and user documentation doesn't exist in this repo, I think it makes sense to restructure like this:
> 
> ```
> repository
> └─── docs/
>     └─── admin/
>          └─── technical-documentation/
>          └─── known-knowns/
>          └─── dev-process/
>          └─── release-process/
>     └─── consultation/
>          └─── portal-iam-helm.chart.md
>          └─── charts/
>          └─── environment/
>          └─── workshops/
>          └─── consultation.md
>     └─── README.md
> ```

@evegufy Thanks for the suggestion! I’ve restructured the documentation according to your recommendations

2024-11-07 07:13 UTC, evegufy approved these changes
looks really good, thank you @shahmargi12

2024-11-07 07:41 UTC, evegufy requested changes
sorry I noticed that there's still a change needed

2024-11-07 07:41 UTC, evegufy commented on docs/README.md
> +- [Workshop 20231005](./consultation/workshops/workshop-20231005.md): Materials and steps from the October 5, 2023 workshop.
```suggestion
The `workshops` folder includes minutes and topics for two workshops:

- [Workshop 20230927](./consultation/workshops/workshop-20230927.md): topics covered during the session of September 27, 2023 workshop.
- [Workshop 20231005](./consultation/workshops/workshop-20231005.md): topics covered during the session of October 5, 2023 workshop.
```

2024-11-07 07:41 UTC, evegufy commented on docs/README.md
> +- [Portal IAM Helm Chart](./consultation/portal-iam-helm-chart.md): Instructions on using the Helm chart for deploying Portal IAM on Kubernetes.
```suggestion
### 1. [charts](./consultation/charts/) and [environments](./consultation/environments/)

The `charts` and `environments` folder contain an **example** helm chart and configuration for a potential deployment improvement discussed during workshops.

- [Portal IAM Helm Chart](./consultation/portal-iam-helm-chart.md): instructions on using this **example** helm chart.
```

2024-11-07 07:41 UTC, evegufy commented on docs/README.md
> +- Key architectural consultation notes and decisions.
```suggestion
### 3. [Consultation Document](./consultation/consultation.md)

- Consultation notes and decisions.
```

2024-11-07 09:05 UTC, shahmargi12 commented
> sorry I noticed that there's still a change needed

Thanks for catching that! I’ve made the change as requested. Let me know if there's anything else that needs updating.

2024-11-07 09:37 UTC, evegufy approved these changes

2024-11-07 09:37 UTC, merged