:memo: Add workshop documentation and references
eclipse-tractusx/portal-iam pull request #26
Opened 2023-09-28 21:05 UTC by rmarting

## Description

Add documentation and references from first Workshop delivered.

## Why

Request by the team instead of the use of Google Slides deck.

## Issue

N/A

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my changes
- [ ] I have successfully tested my changes
- [ ] I have added comments in the default values.yaml file with helm-docs syntax ('# -- ') if relevant for installation
- [X] I have commented my changes, particularly in hard-to-understand areas
- [ ] I have added a copyright and license header in all affected files
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer

2023-10-06 07:20 UTC, rmarting commented
@evegufy All the content was pushed here for your review. Includes the workshop's summaries and the PoC Helm Chart implementation. If you have comments or questions, please, let me know.

Thanks

2023-10-09 13:31 UTC, evegufy commented on charts/portal-iam/.helmignore
Could you please move the 'portal-iam' chart directory to /docs/consultation/ ?
As won't change in the short term to the new chart structure, it's inconvenient to have it in the charts dir as the chart releaser actions works with that directory.

2023-10-09 13:43 UTC, evegufy requested changes
Hi @rmarting the PR looks really good!

Could you please sign the Eclipse Contributor Agreement?:
https://www.eclipse.org/legal/ECA.php
You'd need to create a Eclipse account 
https://accounts.eclipse.org/user/register
and then sign the ECA here:
https://accounts.eclipse.org/user/eca

I also made a comment regarding the location of the portal-iam example chart and there's conflict with the consultation.md file, could you please solve that?

Thank you!

2023-10-09 13:45 UTC, evegufy commented
@rmarting please also update the PR description, it's still from the 1rst workshop, thanks.

2023-10-10 08:26 UTC, rmarting commented
@evegufy Moved the Helm Chart to the new location, however, I am trying to create my Eclipse Foundation account but it is not working, as I am not getting the confirmation email.

The PR is named without references for the first workshop, just the name of my personal branch. Are you asking to change the name of my branch?

Thanks

2023-10-10 09:21 UTC, evegufy commented
> @evegufy Moved the Helm Chart to the new location, however, I am trying to create my Eclipse Foundation account but it is not working, as I am not getting the confirmation email.
> 
> The PR is named without references for the first workshop, just the name of my personal branch. Are you asking to change the name of my branch?
> 
> Thanks

Hi @rmarting thanks for moving the example chart!

Regarding updating the PR description, I just meant updating the main comment of the PR: 
![image](https://github.com/eclipse-tractusx/portal-iam/assets/46191613/8758bb03-8de0-4960-90ef-7c022c8adf39)

Regarding the missing confirmation when creating of the Eclipse Foundation account: That's a bit out of my reach but Ican create a EF Helpdesk issue, I assume you used you RH mail address for creating the account, right?

There's still the conflict in the consultation.md file, could you please solve that?

2023-10-10 11:17 UTC, rmarting commented
Sorry @evegufy as I can see the conflict in the `consultation.md` file, as in the PR that file is safe to be merged. Could you give more context about which conflicts are there?

Updated the PR description, and I am still waiting to the the Eclipse Foundation account. Tested with my RH email, and personal one ... but same results! :disappointed:

2023-10-10 11:37 UTC, evegufy commented
> Sorry @evegufy as I can see the conflict in the `consultation.md` file, as in the PR that file is safe to be merged. Could you give more context about which conflicts are there?
> 
> Updated the PR description, and I am still waiting to the the Eclipse Foundation account. Tested with my RH email, and personal one ... but same results! 😞

@rmarting I'm not sure, I understand your comment correctly but I mean the following conflict:
![image](https://github.com/eclipse-tractusx/portal-iam/assets/46191613/a5634a8e-9576-4ce4-9e89-db6ef5a5b829)
I recommend rebasing to the 'docs/consultation' base branch.

Regarding Eclipse Foundation Account: I'll check how to support and get back to you.

2023-10-10 12:36 UTC, rmarting commented
Done! Just waiting to create the EF account property. The main issue is that the confirmation email do not arrive on time, it is taking several hours, and when I click in the links to confirm, it is expired. I am trying from time to time, but it is always the same issue. I will confirm you when my account is ready (as, this is the only thing pending to do)

2023-10-10 16:31 UTC, rmarting commented
@evegufy Signed my ECA and now all the checks have passed! So, DONE! :tada: :sparkles:

2023-10-11 12:27 UTC, merged