chore: move iam specific docu from assets to iam
eclipse-tractusx/portal-iam pull request #31
Opened 2023-11-16 07:40 UTC by Phil91

## Description

Move the documentation for iam from the assets repo to the iam repo

## Why

To have the documentation at the correct place

## Issue

N/A - Jira Issue: CPLP-3059

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my changes
- [x] I have successfully tested my changes

2023-11-16 17:20 UTC, evegufy commented on docs/technical documentation/01. Introduction.md
> +<br>
As discussed, would be great it you could add a footer like this to all md files https://github.com/eclipse-tractusx/portal-iam/blob/feature/CPLP-3059-docu/docs/consultation/portal-iam-helm-chart.md#notice
if you plan to provide a script for this, even greater :)

2023-11-16 17:24 UTC, evegufy requested changes
as discussed, would be great if you could provide the license files for the png files in the static dir and if you could also copy the script to auto create them https://github.com/eclipse-tractusx/portal-assets/blob/main/scripts/license.sh

and move those [imgs](https://github.com/eclipse-tractusx/portal-iam/tree/feature/CPLP-3059-docu/docs/consultation/img) also to the static dir and reference them accordingly

2023-11-17 07:12 UTC, Phil91 commented on docs/technical documentation/01. Introduction.md
> +<br>
added the footer to all .md files and created the script for it as well :)

2023-11-27 11:37 UTC, evegufy approved these changes

2023-11-27 11:52 UTC, merged